### ISSUE TITLE
{dplyr} and {plyr} may be loaded in inappropriate order

### ISSUE THREAD

**Issue by sinhrks** [hoxo-m/pforeach#1]
Thank you for sharing the great package! 

It is very convenient, but there is a situation that `{plyr}` is loaded after `{dplyr}` inappropriately.
#### Minimal reproducible example:

```
library(pforeach)
library(ggplot2)
library(dplyr)

pforeach(i=1:5)({
  x <- 1
})
# ....
# -------------------------------------------------------------------------------
# You have loaded plyr after dplyr - this is likely to cause problems.
# If you need functions from both plyr and dplyr, please load plyr first, then dplyr:
# library(plyr); library(dplyr)
# -------------------------------------------------------------------------------
# ...

loadedNamespaces()
#  [1] "assertthat" "base"       "codetools"  "colorspace" "compiler"  
#  [6] "datasets"   "DBI"        "digest"     "doParallel" "doRNG"     
# [11] "dplyr"      "foreach"    "ggplot2"    "graphics"   "grDevices" 
# [16] "grid"       "gtable"     "iterators"  "magrittr"   "MASS"      
# [21] "methods"    "munsell"    "parallel"   "pforeach"   "pkgmaker"  
# [26] "plyr"       "proto"      "Rcpp"       "registry"   "reshape2"  
# [31] "rngtools"   "scales"     "stats"      "stringr"    "tools"     
# [36] "utils"      "xtable"  
```

I don't think this is actualy a `{pforeach}` issue, but it is great the package can care the order.

**Comment by hoxo-m** [comment]
I think the problem belongs to the `pforeach`.
That loads packages ordered by alphabet in parallel block.
And `dplyr` < `plyr` in alphabetical order.

But I don't know how to know the correct order of loaded packages.

I can
1. make the `dplyr` to special treatment.
2. consider more general approach.

Or, you can set the correct order of loading packages to `.packages` parameter.

If you have known how to get to know the order of loaded packages, please tell me. 

Example:

``` r
library(pforeach)
library(plyr)
library(dplyr)

pforeach(i=1)({
  iris %>% summarise(count=n())
})
```

```
<simpleError in n(): This function should not be called directly>
```

``` r
pforeach(i=1, .packages=c("plyr","dplyr"))({
  iris %>% summarise(count=n())
})
```

```
  count
1   150
```

**Comment by hoxo-m** [comment]
I changed the order of loading dplyr package into the last.
You can update `pforeach:::update()`.
For the correctness, we must consider the package dependencies.

**Comment by sinhrks** [comment]
Thank you for the effort. It works now.

Remaining minor issue is I still see a warning if `plyr` is not loaded explicitly on the original namespace like below (`ggplot2` requires `plyr`). Thus I assume that we should load all order-dependent packages on the original namespace first, then use `pforeach`.

```
library(pforeach)
library(ggplot2)
library(dplyr)
```
