### ISSUE TITLE
The default behavior difference between foreach and pforeach

### ISSUE THREAD

**Issue by teramonagi** [hoxo-m/pforeach#3]
Because the default combine function is different between foreach and pforeach, the default behaviors differ between foreach and pforeach.

``` r
> result1 <- foreach(i = 1:3) %do% {
+   list(df=iris[1:3, ], summary=summary(iris))
+ }
> class(result1[[1]])
[1] "list"
> library(pforeach)
> result2 <- pforeach(i = 1:3)({
+   list(df=iris[1:3, ], summary=summary(iris))
+ })
> class(result2[[1]])
[1] "data.frame"
```

To solve this issue, we have to write like the following right now in pforeach package.

``` r
> defcombine <- function(a, ...) c(a, list(...))
> result3 <- pforeach(i = 1:3, .combine=defcombine, .init=list())({
+   list(df=iris[1:3, ], summary=summary(iris))
+ })
> class(result3[[1]])
[1] "list"
```

Do you have any idea to deal with this more easily?

You can check the "defcombine" function used in foreach package in the following link:
- https://github.com/cran/foreach/blob/7ec8f3cf08f99ec65b93b900ecc3c0d81b003ed8/R/foreach.R

**Comment by hoxo-m** [comment]
Set `.c=list` to use the default combine function of `foreach`.

``` r
library(foreach)
result1 <- foreach(i = 1:3) %do% {
  list(df=iris[1:3, ], summary=summary(iris))
}

library(pforeach)
result2 <- pforeach(i = 1:3, .c=list)({
  list(df=iris[1:3, ], summary=summary(iris))
})

identical(result1, result2)
```

```
[1] TRUE
```

**Comment by teramonagi** [comment]
Thanks!
That's easy enough!
